# Generated by Django 3.2.16 on 2022-12-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='desc2',
        ),
        migrations.AlterField(
            model_name='team',
            name='img2',
            field=models.ImageField(upload_to='picz'),
        ),
    ]
